### ISSUE TITLE
NSMC (Binary Classification) Data issue

### ISSUE THREAD

**Issue by pminhyung** [Pseudo-Lab/nlp_open_cookbook#2]
[현상]
동일한 하이퍼파라미터 사용에도, KoELECTRA-Base-v3 (monologg/KoELECTRA) 과의  NSMC Accuracy 차이 발생 (0.884, 약 2.2%)

[원인]
현재 master branch의 NSMC 데이터 (train_binary.csv, test_binary.csv) 와 실제 NSMC 밴치마크 데이터 간 차이 확인
- 현재 NSMC 데이터 개수 : 20,000 : 2000 (train : test)
- KoELECTRA repository의 NSMC 데이터 개수 : 150,000: 50,000 (train : test)

![issue1](https://user-images.githubusercontent.com/93268694/165453323-2d276eaf-b6d2-40b7-ab53-9947125e4171.PNG)
![issue2](https://user-images.githubusercontent.com/93268694/165453354-f746220b-c44b-4216-8949-358e8c78cdf1.PNG)

**Comment by DaehanKim** [comment]
아 어쩐지~ 데이터가 간소화된 버전이였군요

**Comment by pminhyung** [comment]
네네 대한님의 kobart 쪽도 ynat은 성능이 잘 나왔는데 nsmc 는 차이가 좀 있었던 이유가 데이터 차이 때문이 아닐까 싶습니다 ㅎㅎ

**Comment by DaehanKim** [comment]
예리한 분석이었습니다 👍
